name: snowplow
description: A new flutter plugin project.
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.wogaaflutter.snowplow
    pluginClass: SnowplowPlugin
